name: arch package

on:
  release:
    types: [published]

jobs:
  build-arch-pkg:
    runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    container:
      image: archlinux:latest
    steps:
      - name: try upgrading git
        run: |
          git config --global --add safe.directory $(realpath .)
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: check files
        run: ls -la 
      - name: Install prerequisites
        run: |
          echo "ParallelDownloads = 10" >> /etc/pacman.conf
          echo "\n" && echo "[multilib]" >> /etc/pacman.conf
          echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
          pacman -Syu base-devel sudo meson python-mako glslang git hub --noconfirm
      - name: makepkg
        run: |
          echo "nobody ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
          chown nobody:nobody pkgbuild
          cd pkgbuild
          sudo -u nobody -- sh -c "makepkg -fsiCc --noconfirm"
      - name: Edit release and add files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          echo "runner workspace ${{ runner.workspace }}"
          echo "github workspace ${{ github.workspace }}"
          ls -la
          pwd
          assets=()
          for pkg in ./pkgbuild/*mangohud*.tar.zst;
            do echo $pkg;
            assets+=("-a" "$pkg")
          done;
          tag_name="${GITHUB_REF##*/}"
          hub release edit "${assets[@]}" -m "" "$tag_name"