name: Update Meson Version

on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Ensure we are on the main branch
        run: git checkout main

      - name: Extract version from release
        id: extract_version
        run: echo "version=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Update meson.build
        run: |
          VERSION=${{ env.version }}
          sed -i "s/^version: .*/version: '${VERSION}'/" meson.build
        
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add meson.build
          git commit -m "Update version to ${{ env.version }}"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:refs/heads/master
